### ISSUE TITLE
'preferredDatePickerStyle' not found on object of type 'DatePicker *'

### ISSUE THREAD

**Issue by andreialecu** [henninghall/react-native-date-picker#223]
**Describe the bug**

While building on AppCenter CI/CD, it seems that the newest version 3.0.3 fails the build with the following error:

```
/Users/runner/work/1/s/node_modules/react-native-date-picker/ios/RNDatePicker/DatePicker.m:58:18: error: property 'preferredDatePickerStyle' not found on object of type 'DatePicker *'
            self.preferredDatePickerStyle = UIDatePickerStyleWheels;
                 ^
/Users/runner/work/1/s/node_modules/react-native-date-picker/ios/RNDatePicker/DatePicker.m:58:45: error: use of undeclared identifier 'UIDatePickerStyleWheels'
            self.preferredDatePickerStyle = UIDatePickerStyleWheels;
                                            ^
2 errors generated.
```

Seems this is caused by https://github.com/henninghall/react-native-date-picker/pull/217

AppCenter is configured to use xcode 11.2.1

**Smartphone (please complete the following information):**

 - react-native-date-picker version 3.0.3

**Comment by andreialecu** [comment]
Fortunately I was able to change the version of xcode to 11.6 and got this resolved. Closing.
